In [19]:
# We are going to implement a kmeans algorithm
# We will code each function separately and then put them together
# we will build a class to hold the functions
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import os

from KmeansClassifier import KmeansClassifier
from sklearn.decomposition import PCA

import KmeansClassifier as kc


import importlib

# Reload the module containing the KmeansClassifier class
importlib.reload(kc.KmeansClassifier)

TypeError: reload() argument must be a module

In [11]:
cwd = os.getcwd()
print(cwd)

/Users/manulabricole/Documents/CDN/MachineLearning/ML3/ML3.2


In [12]:
iris = load_iris()

In [13]:
clf = KmeansClassifier()

In [15]:
clf.load_data(iris)
centroids = clf.init_centroids(random_state = 33)
print(centroids)

TypeError: init_centroids() got an unexpected keyword argument 'random_state'

In [ ]:
clf.compute_distance()
cluster = clf.find_cluster_label()
clf.plot()

[[0.96563239 0.91445658 0.04868422 0.49722739 0.55311674]
 [0.71738159 0.81371068 0.94324256 0.45217738 0.53555741]
 [0.98118334 0.43120714 0.48580857 0.64227128 0.70266981]]
