In [26]:

import pandas as pd
import numpy as np

from sklearn.datasets import load_iris


In [27]:
cwd = os.getcwd()
print(cwd)

/Users/manulabricole/Documents/CDN/MachineLearning/ML3/ML3.2


In [ ]:
iris = load_iris()

In [47]:
from KmeansClassifier import KmeansClassifier
clf = KmeansClassifier()
clf.load_data(iris)
clf.show_data()

AttributeError: 'KmeansClassifier' object has no attribute 'show_data'

In [37]:
print(centroids)

None


In [44]:
import numpy as np

# Create an example array of points with 1000 rows and 5 columns
points = np.random.rand(1000, 5)

# Set the number of random points to select
k = 3

# Use np.random.choice to select k random points from the array
random_points = points[np.random.choice(points.shape[0], k, replace=False)]

# Print the selected random points
print(random_points)


[[0.96563239 0.91445658 0.04868422 0.49722739 0.55311674]
 [0.71738159 0.81371068 0.94324256 0.45217738 0.53555741]
 [0.98118334 0.43120714 0.48580857 0.64227128 0.70266981]]
